### ISSUE TITLE
Internal/runtime errors do not reach outer application layers (when testing)

### ISSUE THREAD

**Issue by otsakir** [hishamhm/restserver#13]
For example:
```
if not input then
      return fail(self, wreq, 400, "Bad Request - Your request fails schema validation: "..err)
end
```
If for some reason 'err' is nil (which happened in a troubleshooting session) you get a misleading 500 response. It's the '..' concatenations that fails and fail() is not really called.

You end up with a cryptic 500 error and no indication where/why this happened. There should me a mechanism or log for such runtime trouble.

This behavior has been observed when testing form luaunit. In direct execution it should work ok.

**Comment by hishamhm** [comment]
Getting a 500 at the client is generally expected on runtime errors like this (which are coding errors — the code their should either ensure that `err` is never nil or do `(err or "")`). In other frameworks these situations generally produce logs on the server side instead.

**Comment by otsakir** [comment]
False alarm. Even in the test env  HTTP response body contains the error description. Closing the issue.

**Comment by otsakir** [comment]
> Getting a 500 at the client is generally expected on runtime errors like this (which are coding errors — the code their should either ensure that `err` is never nil or do `(err or "")`). In other frameworks these situations generally produce logs on the server side instead.

Right. I agree for the (err or "") practice. And for the 500 for runtime stuff.

There will be cases though where we do need the coding error to reach the surface. That's why i investigated further. But even for these cases it proved that the error was part of the response but ...it went under the radar :-(.
