### ISSUE TITLE
Access to authentication information like logged user etc.

### ISSUE THREAD

**Issue by otsakir** [hishamhm/restserver#15]
Sometimes, the application should adapt its behaviour to the user that is making a REST request. I found no way to access the authorization header or other higher level related piece of information. I also digged through lower levels of the stack, checked WSAPI and xavante code and docs but couldn't solve this.

@hishamhm , to  you have any idea if this is available somehow or how this would be implemented ? 
Btw, i created this issue https://github.com/keplerproject/wsapi/issues/46 but i'm not sure if the project is really active there.

**Comment by otsakir** [comment]
False, alarm. I digged further. It seems that The HTTP_AUTHORIZATION variable is set in the environment and can easily be retrieved. It is a dynamic 'getter' though so it was displayed from the inspect() function. Hence the confusion. Moving on...

1. Provide authentication functionality in the resource entry. A function that would take the env, do the authentication and return its status, the name of the authenticated user etc. For starters, that would be done at the resource entry level. Maybe an `auth` function property along with `method`, `path` etc.  

2. In `wsapi_handler_with_self()` invoke the `auth` method and inject the result as one more parameter of the handler function. If one has specified the 'auth' function for an entry, one more parameter will be reserved in the handler.

**Comment by otsakir** [comment]
I patched restserver.lua so that it looks for `auth` property in a resource entry, authenticate, throw 401 in case of error or propagate user info to the entry handler if all goes well.

Next, i'll establish the same auth callback in a larger scope. Probably in the resource itself.

**Comment by hishamhm** [comment]
@otsakir I don't think the keplerproect/wsapi project is active, but for WSAPI-related questions the best people to ping are @mascarenhas or @jasonsantos, they definitely know more about it than I do :)

**Comment by otsakir** [comment]
Closing issue. Maybe, at some point move auth in a separate rock.
