### ISSUE TITLE
breaking change after last commit #1

### ISSUE THREAD

**Issue by vince62s** [hishamhm/restserver#3]
Hisham,

We are using your code and it worked fine until the merge of #1 

I have no clue of what it is supposed to but now, when I send the same POST as before, I am getting some sort of error I cannot explain, like here (my client code is based on your example):

[11/10/17 16:05:33 DEBUG] receiving request	
{
  GET : {...}
  cookies : {...}
  params : {...}
  query_string : ""
  parse_post : function: 0x41784b60
  method : "POST"
  POST : 
    {
      post_data : "[{ "src" : "international migration" }]"
    }
  path_info : "/translator/translate"
  script_name : ""
  env : 
    {
      REQUEST_METHOD : "POST"
      APP_PATH : ""
      DOCUMENT_ROOT : ""
      CONTENT_TYPE : "application/json"
      PATH_INFO : "/translator/translate"
      QUERY_STRING : ""
      SCRIPT_NAME : ""
      input : 
        {
          length : 39
          read : function: 0x4177d988
        }
      CONTENT_LENGTH : "39"
      HTTP_COOKIE : ""
      error : file (0x7f7788e141c0)
    }
  app_path : ""
  doc_root : ""
}

**Comment by hishamhm** [comment]
Hi, I tried to keep things compatible in the latest code, so if anything broke it's definitely a bug. I am having a hard time interpreting your log, though. Can you post a minimal example that used to work before but doesn't work now?
