### ISSUE TITLE
bug in fail() messes error reporting

### ISSUE THREAD

**Issue by otsakir** [hishamhm/restserver#8]
I keep getting the following for any type of json validation error (line number are altered since i was trying to pinpoint the problem with logging statements):

/usr/local/share/lua/5.1/restserver.lua:137: attempt to concatenate local 'err' (a nil value)
stack traceback:
        /usr/local/share/lua/5.1/restserver.lua:137: in function </usr/local/share/lua/5.1/restserver.lua:124>
        (tail call): ?
        (tail call): ?
        (tail call): ?
stack traceback:
        /usr/local/share/lua/5.1/coxpcall.lua:47: in function </usr/local/share/lua/5.1/coxpcall.lua:45>
        (tail call): ?
        (tail call): ?
        (tail call): ?
        /usr/local/share/lua/5.1/wsapi/xavante.lua:89: in function </usr/local/share/lua/5.1/wsapi/xavante.lua:44>
        (tail call): ?
        (tail call): ?
        (tail call): ?
        /usr/local/share/lua/5.1/xavante/httpd.lua:64: in function </usr/local/share/lua/5.1/xavante/httpd.lua:42>
</pre>

**Comment by hishamhm** [comment]
fixed by #9 :)
